Week-6-Rails/manderley_cast/config/routes.rb
Manderley::Application.routes.draw do
  devise_for :users
  resources :movies do
    resources :comments, shallow: true

    get 'up', to: 'movies#up', as: :thumbs_up
    get 'down', to: 'movies#down', as: :thumbs_down

    get "cast/new", to: 'movies#new_cast', as: :new_cast
    post "cast", to: 'movies#create_cast', as: :create_cast
  end

  resources :people, shallow: true do
    get 'up', to: 'people#up', as: :thumbs_old_up
    get 'down', to: 'people#down', as: :thumbs_old_down
  end

root 'movies#index'

end

Week-6-Rails/manderley_cast/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy, :new_cast, :create_cast, :up, :down]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
    authorize @movie
  end

  # GET /movies/1/edit
  def edit
    authorize @movie
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    authorize @movie

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render action: 'show', status: :created, location: @movie }
      else
        format.html { render action: 'new' }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update

    authorize @movie

    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy

    authorize @movie

    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }

      format.js do
        render(
          partial: 'destroy_animation',
          locals:  { resource: @movie }
        )
      end

    end
  end

  # GET /movies/1/cast/new
  def new_cast
    @cast = @movie.casts.build
  end

  # POST   /movies/:movie_id/cast
  def create_cast
    @cast = @movie.casts.build(cast_params)
    respond_to do |format|
      if @cast.save
        format.html { redirect_to @movie, notice: "Cast added" }
        format.json { render action: :show, status: :created, location: @movie}
      else
        format.html { render action: :new }
        format.json { render json: @cast.errors, status: :unprocessable_entity}
      end
    end
  end

  def up
    #vote = Vote.user(current_user).movie(@movie).first
    #unless vote
      #vote = Vote.user(current_user).movie(@movie).build
    #end
    vote = Vote.user(current_user).movie(@movie).find_or_initialize_by({})

    vote.liked

    authorize vote, :save? # le estamos diciendo con que politica utorizar, por
                           # defecto en la politica tendria que haber def up?
    vote.save

    redirect_to movie_path(@movie)
  end

  def down
    vote = Vote.user(current_user).movie(@movie).find_or_initialize_by({})

    vote.disliked

    authorize vote, :save?
    vote.save

    redirect_to movie_path(@movie)
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:movie_id] || params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :year, :duration, :synopsis)
    end

    def cast_params
      params.require(:cast).permit(:person_id, :role)
    end
end

Week-6-Rails/manderley_cast/app/helpers/movies_helper.rb
module MoviesHelper
end

Week-6-Rails/manderley_cast/app/views/movies/_cast_form.html.erb
<%= form_for(@cast, url: movie_create_cast_path(@movie)) do |f| %>
  <% if @cast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cast.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @cast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id %>
    <%= f.select :person_id,
    Person.all.map {|p| [ p.complete_name, p.id ] } %>
  </div>

  <div class="field">
    <%= f.label :role %>
    <%= f.select :role, 
       Cast::ROLES.map {|r| [r.titleize, r]} %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Week-6-Rails/manderley_cast/app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br>
    <%= f.text_field :synopsis %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Week-6-Rails/manderley_cast/app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>
<%= link_to 'Add person', new_person_path(@movie) %>

Week-6-Rails/manderley_cast/app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Year</th>
      <th>Duration</th>
      <th>Synopsis</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
      <%= content_tag_for(:tr, @movies) do |movie| %>
        <td><%= movie.title %></td>
        <td><%= movie.year %></td>
        <td><%= movie.duration %></td>
        <td><%= movie.synopsis %></td>
        <td><%= link_to 'Show', movie %></td>

        <% if policy(movie).update? %>
          <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <% end %>

        <% if policy(movie).destroy? %>
          <td><%= link_to 'Destroy', movie, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      <% end %>
  </tbody>
</table>

<br>

<% if policy(Movie.new).create? %>
  <%= link_to 'New Movie', new_movie_path %>
<% end %>

Week-6-Rails/manderley_cast/app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

Week-6-Rails/manderley_cast/app/views/movies/new_cast.html.erb
<h1>New cast</h1>

<%= render 'cast_form' %>

<%= link_to 'Back', @movie %>

Week-6-Rails/manderley_cast/app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @movie.duration %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @movie.synopsis %>
</p>



<p>
  <% if @movie.people.empty? %>
  <strong> No people in here</strong>
  <% else %>
    <strong>People:</strong>
    <ul>
      <% @movie.casts.each do |c| %>
        <li>
          <%= c.person.complete_name %>
          (
          <%= c.role.titleize %>
          )


        </li>
      <% end %>
    </ul>
  <% end %>
</p>


<% if policy(Vote.user(current_user).movie(@movie).find_or_initialize_by({})).save? %>
  <div id="voting_system">
    <%= link_to "I like it!", movie_thumbs_up_path(@movie), method: :post %>
    <%= link_to "I didnt like it!", movie_thumbs_down_path(@movie), method: :post %>
  </div>
<% end %>

<% if @movie.votes.present? %>
  <div id="votes">
    <%= @movie.likes.size %> out of <%= @movie.votes.size %> people like this
  </div>
<% end %>

<h4>Comments</h4>
<%= render @movie.comments %>

<button id="add-comment-button">Comment</button>
  <% if policy(@movie.comments.build).create? %>
    <div id="add-comment">
    <h4>Add a comment:</h4>
    <%= render 'comments/form' %>
  <% end %>
</div>


<%= link_to 'Add cast', movie_new_cast_path(@movie) %> |
<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>