Week-4-Rails/challenges/config/routes.rb
Rails.application.routes.draw do

  resources :challenges do
    resources :votes
  end

  get '/', to: 'site#home', as: "home"

end

Week-4-Rails/challenges/app/models/challenge.rb
class Challenge < ActiveRecord::Base

  has_many :votes, dependent: :destroy

  validates :name,        presence: true

  before_save :set_description_to_default_value

  mount_uploader :poster, PosterUploader



  private

  def set_description_to_default_value
    self.description = "Default value"
  end

end

Week-4-Rails/challenges/app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :challenge

  validates :email, format: { with: EmailAddressValidator::Regexp::ADDR_SPEC}

  def self.num_of_votes challenge_id
    Vote.where(challenge_id: challenge_id).count
  end

end

Week-4-Rails/challenges/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Week-4-Rails/challenges/app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  before_filter :load_challenge, only: [:show, :update, :edit, :destroy]


  def new
    @challenge = Challenge.new
  end

  def create
    @challenge = Challenge.new challenge_params
    if @challenge.save
      flash.now[:notice] = "Challenge saved!"
      redirect_to challenges_path
    else
      flash.now[:error] = "Error on save!, challenge not saved"
      render 'new'
    end
  end

  def index
    @challenges = Challenge.where("name ilike ?", str_to_search(params[:q])).
      order(created_at: :desc).paginate(:page => params[:page])

  end

  def show
    if @challenge
      @vote      = @challenge.votes.new
      @num_votes = Vote.num_of_votes(params[:id])
    else
      redirect_to '/404'
    end
  end

  def edit
  end

  def update
    if @challenge.update_attributes challenge_params
      flash.now[:notice] = "Challenge updated!"
    else
      flash.now[:error] = "Error on update!, challenge not saved"
    end
    redirect_to '/challenges'
  end

  def destroy
    @challenge.destroy
    redirect_to '/challenges', notice: 'Challenge deleted correct'
  end



  private

  def load_challenge
    @challenge = Challenge.where(id: params[:id]).first
  end

  def challenge_params
    params.require(:challenge).permit(:name, :description, :poster)
  end

  def str_to_search str
    search = params[:q] || ""
    "%#{search}%"
  end

end

Week-4-Rails/challenges/app/controllers/site_controller.rb
class SiteController < ApplicationController

  def home
    render 'home'
  end

end

Week-4-Rails/challenges/app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @vote = Challenge.find(params[:challenge_id]).votes.new vote_params
    if @vote.save
      flash[:notice] = "Thanks for vote!"
      ChallengeMailer.new_vote(Challenge.find(params[:challenge_id]), @vote).deliver
      redirect_to challenge_path(params[:challenge_id])
    else
      flash[:error] = "Error, We cant add your vote"
      redirect_to challenge_path(params[:challenge_id])
    end
  end



  private

  def vote_params
    params.require(:vote).permit(:email)
  end

end

Week-4-Rails/challenges/app/helpers/application_helper.rb
module ApplicationHelper

  def flash_message
    if flash[:error]
      show_flash(flash[:error], "error")
    elsif flash[:notice]
      show_flash(flash[:notice], "notice")
    end
  end

  def previus_page?
    params[:page].present? && params[:page].to_i > 1
  end

  def next_page?
    current_page = params[:page].to_i
    # except: desconcatenar
    total = @challenges.except(:limit).except(:offset).count
    total_pages = (total / 10) + 1

    current_page < total_pages
  end



  private

  def show_flash message, css_class
    content_tag :div, class: "message #{css_class}" do
      content_tag :p do
        message
      end
    end
  end

end

Week-4-Rails/challenges/app/helpers/challenges_helper.rb
module ChallengesHelper
end

Week-4-Rails/challenges/app/helpers/site_helper.rb
module SiteHelper
end

Week-4-Rails/challenges/app/helpers/votes_helper.rb
module VotesHelper
end

Week-4-Rails/challenges/app/views/challenges/_form.html.erb
<%= flash_message %>

<% if @challenge.errors.any? %>
  <ul>
    <% @challenge.errors.full_messages.each do |err_msg| %>
      <li><%= err_msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @challenge, html: {multipart: true} do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :poster %>
  <%= f.file_field :poster %>

  <%= f.submit 'Save challenge!' %>

<% end %>

Week-4-Rails/challenges/app/views/challenges/edit.html.erb
<h2>Edit challenge:</h2>

<%= render 'form' %>

<%= link_to "Cancel", challenges_path %>

Week-4-Rails/challenges/app/views/challenges/index.html.erb
<%= link_to "Home", home_path %>
<%= link_to "+Add challenge", new_challenge_path %>

<%= form_tag challenges_path, method: :get do %>
  <%= search_field_tag :q, params[:q], placeholder: "Search a challenge" %>
<% end %>

<h2>Challenge list</h2>

<table>
  <tr>
    <th></th>
    <th>Challenge name</th>
    <th>Date of creation</th>
  </tr>

  <% @challenges.each do |ch| %>
    <tr>
      <td><%= image_tag ch.poster.url(:thumb) %></td>
      <td><%= link_to ch.name, challenge_path(ch) %></td>
      <td><%= ch.created_at %></td>
    </tr>
  <% end %>

</table>

<%= will_paginate @challenges %>

Week-4-Rails/challenges/app/views/challenges/new.html.erb
<h2>Add challenge:</h2>

<%= render 'form' %>

<%= link_to "Cancel", home_path %>

Week-4-Rails/challenges/app/views/challenges/show.html.erb
<%= link_to "Challenges list", challenges_path %>
<%= link_to "+Add challenge", new_challenge_path %>

<%= image_tag @challenge.poster.url %>

<h3><%= truncate(@challenge.name, length: 20) %></h3>
<p><%= simple_format(@challenge.description) %></p>
<h5>Date of creation: <%= @challenge.created_at %></h5>

<%= link_to "Edit", edit_challenge_path %>
<%= link_to "Delete", challenge_path(@challenge), 
  method: :delete, 
  data: {confirm: 'Are you sure?'} 
%>

<p><%= pluralize(@num_votes, 'vote', 'votes')%></p>
<%= flash_message %>
<%= form_for [@challenge, @vote] do |f| %>

  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit 'Vote' %>

<% end %>

Week-4-Rails/challenges/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Challenges</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Week-4-Rails/challenges/app/views/site/home.html.erb
<h1>Super Challenges!!!!</h1>
<%= link_to "New challenge", new_challenge_path %>
<%= link_to "View challenges", challenges_path %>