Week-6-Rails/manderley_cast/config/routes.rb
Manderley::Application.routes.draw do
  devise_for :users
  resources :movies do
    resources :comments, shallow: true

    get 'up', to: 'movies#up', as: :thumbs_up
    get 'down', to: 'movies#down', as: :thumbs_down

    get "cast/new", to: 'movies#new_cast', as: :new_cast
    post "cast", to: 'movies#create_cast', as: :create_cast
  end

  resources :people, shallow: true do
    get 'up', to: 'people#up', as: :thumbs_old_up
    get 'down', to: 'people#down', as: :thumbs_old_down
  end

root 'movies#index'

end

Week-6-Rails/manderley_cast/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :movie
  belongs_to :user


  validates_presence_of :body
  validates_length_of :body, maximum: 500
  validates_presence_of :movie

end

Week-6-Rails/manderley_cast/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_comment, only: [:show, :edit, :destroy, :update]
  before_action :set_movie, only: [:index, :new, :create, :destroy]
  before_action :authenticate_user!, except: [:index]


  def create
    @comment = @movie.comments.build comment_params
    @comment.user = current_user

    authorize @comment

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @movie, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    authorize @comment
  end

  def update
    authorize @comment
    if @comment.update comment_params
      redirect_to movie_path(@comment.movie)
    else
      render action: 'edit'
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end
 
  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:body)
  end

end

Week-6-Rails/manderley_cast/app/helpers/comments_helper.rb
module CommentsHelper

  def author_display_name comment
    str = comment.user.username.capitalize
    unless comment.user.plain?
      str += " (#{comment.user.role})"
    end
  end

end

Week-6-Rails/manderley_cast/app/views/comments/_comment.html.erb
  <p>
    <strong>Author:</strong>
    <div class="user <%= comment.user.role %>">
      <%= author_display_name comment %>
    </div>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <div class="actions">
    <% if policy(comment).update? %>
      <%= link_to 'Edit', edit_comment_path(comment) %>
    <% end %>
  </div>

Week-6-Rails/manderley_cast/app/views/comments/_form.html.erb
<%= form_for([@movie, @movie.comments.build]) do |f| %>
  <p>
    Write your comment here:<br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

Week-6-Rails/manderley_cast/app/views/comments/edit.html.erb
<%= form_for @comment do |f| %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  
  <div class="actions">
    <%= f.submit 'Update' %>
  </div>

<% end %>