Week-6-Rails/manderley_cast/config/routes.rb
Manderley::Application.routes.draw do
  devise_for :users
  resources :movies do
    resources :comments, shallow: true

    get 'up', to: 'movies#up', as: :thumbs_up
    get 'down', to: 'movies#down', as: :thumbs_down

    get "cast/new", to: 'movies#new_cast', as: :new_cast
    post "cast", to: 'movies#create_cast', as: :create_cast
  end

  resources :people, shallow: true do
    get 'up', to: 'people#up', as: :thumbs_old_up
    get 'down', to: 'people#down', as: :thumbs_old_down
  end

root 'movies#index'

end

Week-6-Rails/manderley_cast/app/models/person.rb
class Person < ActiveRecord::Base
  has_many :casts
  has_many :movies, through: :casts

  has_many :oldvotes
  has_many :old,
             ->() { old },
             class_name: 'Oldvote'
  has_many :notOld,
             ->() { notOld },
             class_name: 'Oldvote'


  validates_presence_of :first_name, :last_name

  def complete_name
    "#{self.first_name} #{self.last_name}"
  end
end

Week-6-Rails/manderley_cast/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, except: [:create, :new, :index]

  def index
    @people = Person.all
  end

  def show
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new person_params

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully added.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end

  end

  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to movie }
      format.json { head :no_content }
    end
  end

  def edit
  end

  def update
  end

  def up
    oldVote = Oldvote.user(current_user).movie(@movie).cast.find_or_initialize_by({})

    oldVote.old

    authorize oldVote, :save?
    oldVote.save

    rediret_to person_path(@person)
  end

  def down
    oldVote = Oldvote.user(current_user).movie(@movie).cast.find_or_initialize_by({})

    oldVote.notOld

    authorize oldVote, :save?
    oldVote.save

    rediret_to person_path(@person)
  end



    private
  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def person_params
    params.require(:person).permit(:first_name, :last_name)
  end

end

Week-6-Rails/manderley_cast/app/helpers/people_helper.rb
module PeopleHelper
end

Week-6-Rails/manderley_cast/app/views/people/_form.html.erb
<%= form_for([@person]) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Week-6-Rails/manderley_cast/app/views/people/_person.html.erb
<li>
  <%=person.complete_name %>
</li>

Week-6-Rails/manderley_cast/app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

Week-6-Rails/manderley_cast/app/views/people/show.html.erb
<%= @person.first_name %>

<% if policy(Oldvote.user(current_user).find_or_initialize_by({})).save? %>

  <div id="voting_system">
    <%= link_to "Old!", person_thumbs_old_up_path(@person) %>
    <%= link_to "Not old!", person_thumbs_old_down_path(@person) %>
  </div>

<% end %>

<div id="votes">
  <%= @person.old.size %> out of <%= @person.oldvotes.size %> people like this
</div>